// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $clients_index from "./routes/clients/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $ClientList from "./islands/ClientList.tsx";
import * as $ClientsPage from "./islands/ClientsPage.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Map from "./islands/Map.tsx";
import * as $Menu from "./islands/Menu.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/clients/index.tsx": $clients_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ClientList.tsx": $ClientList,
    "./islands/ClientsPage.tsx": $ClientsPage,
    "./islands/Counter.tsx": $Counter,
    "./islands/Map.tsx": $Map,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
